// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdx9PxrjxDFZ5HdIgbYorBaus-dTr-zvI',
    appId: '1:292937259242:web:18f46316357606719bdf93',
    messagingSenderId: '292937259242',
    projectId: 'flashlearn-c041c',
    authDomain: 'flashlearn-c041c.firebaseapp.com',
    storageBucket: 'flashlearn-c041c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CVDlQh7ftfaej8lQzu8kj5zkYgqFaWQ',
    appId: '1:292937259242:android:b4c25e2282bb1b7c9bdf93',
    messagingSenderId: '292937259242',
    projectId: 'flashlearn-c041c',
    storageBucket: 'flashlearn-c041c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCweHsnYmXAu3wK-nGioIeme6oMB0yNelc',
    appId: '1:292937259242:ios:68d6aa200fbb4ff69bdf93',
    messagingSenderId: '292937259242',
    projectId: 'flashlearn-c041c',
    storageBucket: 'flashlearn-c041c.appspot.com',
    iosClientId: '292937259242-eftgun5o03gnocth8e5pjtp7vi0g5mud.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashlearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCweHsnYmXAu3wK-nGioIeme6oMB0yNelc',
    appId: '1:292937259242:ios:4659fdfa978cb1b09bdf93',
    messagingSenderId: '292937259242',
    projectId: 'flashlearn-c041c',
    storageBucket: 'flashlearn-c041c.appspot.com',
    iosClientId: '292937259242-s5jf64n2ido08tf99dos0maj41b0ub8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashlearn.RunnerTests',
  );
}
